#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# 把六个 harness 命令装到 PATH：go-harness / go-grpc-harness / fullstack-harness /
# go-pkg-harness / laravel-harness / laravel-fullstack-harness
#
# 用法：
#   bash install.sh                    # 装到 ~/go/bin
#   HARNESS_BIN_DIR=~/.local/bin bash install.sh
#
# 生成的是几行长的包装脚本，直接 exec 本仓库的 scripts/harness-init.sh，
# 所以改了仓库里的 guides / 规则 / 安装脚本立即生效，不需要重装。
# 仓库移动位置后重跑一次即可。
# ============================================================

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
BIN_DIR="${HARNESS_BIN_DIR:-${HOME}/go/bin}"
MARKER="# generated by harness-engineering/install.sh"

mkdir -p "${BIN_DIR}"

installed=0
for dir in "${ROOT_DIR}"/*/; do
    name="$(basename "${dir}")"
    [ -f "${dir}setup.sh" ] || continue
    target="${BIN_DIR}/${name}"
    if [ -e "${target}" ] && ! grep -Fqs "${MARKER}" "${target}"; then
        echo "  ⚠ ${target} 已存在且不是本脚本生成的，已替换"
    fi
    cat > "${target}" <<EOF
#!/usr/bin/env bash
${MARKER}
# 实际逻辑在仓库里，改仓库即生效；仓库移动后重跑 install.sh 刷新路径。
HARNESS_CMD_NAME="${name}" exec bash "${ROOT_DIR}/scripts/harness-init.sh" "${name}" "\$@"
EOF
    chmod +x "${target}"
    echo "  ✓ ${target}"
    installed=$((installed + 1))
done

echo ""
echo "已安装 ${installed} 个命令到 ${BIN_DIR}，在项目目录直接执行命令名即可（如 go-harness）。"
case ":${PATH}:" in
    *":${BIN_DIR}:"*) ;;
    *) echo "⚠ ${BIN_DIR} 不在 PATH 里，把它加进 shell 配置后再用。" ;;
esac
